FROM node:20-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# package.json과 pnpm-lock.yaml만 먼저 복사
COPY package*.json pnpm-lock.yaml ./

# 의존성 설치
RUN pnpm install

# 소스 코드 복사
COPY . .

EXPOSE 3000

CMD ["pnpm", "start:dev"]
